### ISSUE TITLE
PythonコードのLintが通るようにする

### ISSUE THREAD

**Issue by dotneet** [digitaldemocracy2030/polimoney#64]
今後徐々にシステムが複雑化していくと思うので、linterの恩恵が十分に受けられるようにしておきたい。
ruffのツールは導入したが、エラーが多いためチェックは無効かしている状態。

pyproject.toml でruffのチェックを有効化する。

```toml
[tool.ruff.lint]
select = ["ALL"]
```

下記のコマンドでチェックが通るようにする。

`poetry run ruff check .`
